### ISSUE TITLE
Position of Focused Text Field

### ISSUE THREAD

**Issue by PatrickDiallo23** [rodrigobastosv/ensure_visible_when_focused#1]
Can you add a method that adjusts the position of a focused of Text Field to be in center of the screen for a better UX in completing a form or creating account etc? Thanks

**Comment by rodrigobastosv** [comment]
Hey @PatrickDiallo23 , thanks for using this package.

This PR https://github.com/rodrigobastosv/ensure_visible_when_focused/pull/3 probably solves this issue. Its already released on version 1.1.1 on pub.dev.

I'll close this issue for now, but feel free to reopen if needed.
